name: Update Gold Prices Daily

on:
  schedule:
    # Runs every day at 6:00 AM IST (12:30 AM UTC)
    - cron: '30 0 * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  update-prices:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install @google/generative-ai
      
      - name: Fetch gold prices from Gemini
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: node scripts/fetch-gold-prices.js
      
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add public/gold-prices.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update gold prices [skip ci]" && git push)